### ISSUE TITLE
Hi. Предложение по очистке таблицы логов.

### ISSUE THREAD

**Issue by KiryakovDenis** [andorei/atop-plsql#1]
Привет. 
Классное оформленное решение для захвата изменений. Сам сейчас занимаюсь похожим решением, поскольку денег на golden Gate не дают.
Есть мысль по поводу таблицы логов. Предлагаю ее секционировать по диапазону дат, и по необходимости удалять одну из старых секций. Работает более эффективно чем удаление с фиксацией каждые 10000 строк. Если интересно, могу тестовый пример выслать. Решение уже работает в системе аудита.  
KiryakovDenis@gmail.com

**Comment by andorei** [comment]
Привет, Денис.
Спасибо за отзыв. Предложение по секционированию понятно, оно имеет свои преимущества. Буду иметь в виду на будущее, пока не планирую что-то менять.
